### ISSUE TITLE
Report function no longer functional

### ISSUE THREAD

**Issue by coreylawrence** [International-Soil-Radiocarbon-Database/ISRaD#69] opened 2018-10-09 20:41 UTC
@greymonroe 
The basic report function for entry_stats is failing in the current version of the r-package. See the error below:
> er_stat<-reports(ISRaD_data, report="entry_stats")
Error in cbind_all(x) : Argument 2 must be length 0, not 1

**Comment by greymonroe** [comment] 2018-10-09 20:49
caused by same issue in #68

**Comment by greymonroe** [comment] 2018-10-09 20:58
should be fixed with last commit

**Closed by greymonroe** 2018-10-09 20:58 UTC
