### ISSUE TITLE
QAQC check for lyr_bot>lyr_top

### ISSUE THREAD

**Issue by 1Vicky1** [International-Soil-Radiocarbon-Database/ISRaD#124] opened 2018-12-04 07:47 UTC
It may be useful to have QAQC check that lyr_bot is higher than lyr_top for each layer. (I just found an ingested template with switched lyr_bot and lyr_top for few litter layers, I sent a corrected version to info.israd@gmail.com)

**Comment by jb388** [comment] 2018-12-04 09:11
Great idea, Olga. I just built a function like that and identified three entries with issues: Clark_2002, Lawrence_2015, and Phillips_2013. I see you updated Lawrence_2015, so I'll fix the other ones and then implement the function in QAQC.

**Comment by coreylawrence** [comment] 2018-12-04 15:01
So just to be clear. The litter layer notation was intentional in some of these studies. Where did we end up on how we would deal with depth for ISRaD. 

The issue is, with the Lawrence template for example, the organic layers were not included in the original study. For that work, depth started at zero corresponding to the organic mineral interface. The organic incubations were added latter and the inverse depth representation was used. By just switching the values in that study, you end up with a case where the organic layers overlap the mineral layers, which is not correct. I also don't think it is correct to "shift" the mineral depths because then the depth increments are offset from the original study... 

A better solution might be to fill new depth range column(s) in ISRaD extra, in order to implement a standard depth notation. Trick is being able to recognize the various depth conventions that are used.

**Comment by jb388** [comment] 2018-12-04 17:32
We have a standard depth convention with the mineral/organic interface = 0, thus there shouldn't be any overlapping depths if the litter layers are represented with negative values.

**Comment by 1Vicky1** [comment] 2018-12-04 18:02
Yes, what I've understood from Alison and what is now also mentioned in the [Contribute webpage](https://international-soil-radiocarbon-database.github.io/ISRaD/contribute/), we should convert the original conventions to the mineral-organic interface = 0 convention where possible when filling in the template.

**Comment by greymonroe** [comment] 2018-12-19 18:47
@jb388 did you add this to QAQC? If so, can we close this issue?

**Comment by jb388** [comment] 2018-12-19 19:33
Yes, I added this two weeks ago.

**Closed by jb388** 2018-12-19 19:33 UTC
