### ISSUE TITLE
ISRaD.getdata() - how do I update data?

### ISSUE THREAD

**Issue by aahoyt** [International-Soil-Radiocarbon-Database/ISRaD#192] opened 2019-06-20 14:57 UTC
ISRaD_extra <-ISRaD.getdata(directory = mydir, dataset="full", extra = T)

This doesn't update with the latest data, but just returns the one I already had. What should I use instead so that this command will update with the latest data from the website? (without updating the package)

Thanks!

**Comment by greymonroe** [comment] 2019-06-20 14:58
Hmm let me check. I will be working on this and everything else ISRaD related through the weekend,

**Comment by jb388** [comment] 2019-06-20 16:51
Could be the same issue Sophie was having: Did you delete the old versions of the data in the directory you set in the function? If not, the function won't retrieve new ones. 

It is working for me.

**Comment by aahoyt** [comment] 2019-06-20 18:45
Yup, that works! What about making it automatically replace the existing data with the new data though?

**Comment by greymonroe** [comment] 2019-06-21 07:44
Yea that’s definitely doable.

**Comment by greymonroe** [comment] 2019-06-22 08:06
Should be fixed in the last commit. getdata now has force_download parameter. I decided not to make it automatically download data because there may be cases when people want to work with an older version of the database and we dont want to replace their local file without them setting force_download = T.

**Comment by aahoyt** [comment] 2019-06-22 12:19
fyi, the updated function only worked for me after I deleted the old existing data from the folder. When I ran the updated function before I had deleted the old data, it gave the following errors below:

Error:
> ISRaD_only <-ISRaD.getdata(directory = mydir, dataset="full", extra = F, force_download = F)
**Error in gzfile(file) : invalid 'description' argument**

> ISRaD_only <-ISRaD.getdata(directory = mydir, dataset="full", extra = F, force_download = T)

 ISRaD_database_files not found...
 Downloading database files from. https://github.com/International-Soil-Radiocarbon-Database/ISRaD/raw/master/ISRaD_data_files/database/ISRaD_database_files.zip 
trying URL 'https://github.com/International-Soil-Radiocarbon-Database/ISRaD/raw/master/ISRaD_data_files/database/ISRaD_database_files.zip'
Content type 'application/zip' length 10238477 bytes (9.8 MB)
downloaded 9.8 MB
 Unzipping database files to C:/Users/Alison/Dropbox (MIT)/14Constraint/Research/Incubation Synthesis//ISRaD_database_files ...
**Error in gzfile(file) : invalid 'description' argument**

#Examples without the extra argument:
> ISRaD_extra <-ISRaD.getdata(directory = mydir, dataset="full", extra = T)
Error in gzfile(file) : invalid 'description' argument
> ISRaD_only <-ISRaD.getdata(directory = mydir, dataset="full", extra = F)
Error in gzfile(file) : invalid 'description' argument

**Comment by greymonroe** [comment] 2019-06-22 14:40
what was the value of mydir in the examples above?

**Comment by aahoyt** [comment] 2019-06-22 15:36
mydir <- "C:/Users/Alison/Dropbox (MIT)/14Constraint/Research/Incubation Synthesis/"

Also, I no longer have that error if I run the function now with files already in the folder, although now the files I have are already the latest ones, while before I was running it with earlier files in the folder.

**Comment by greymonroe** [comment] 2019-06-22 15:56
Hmm, had you manually changed any of the files in there?

**Comment by aahoyt** [comment] 2019-06-22 16:41
Nope!

If there's no obvious reason it happened, maybe it's not worth worrying about unless it comes up again....

**Comment by greymonroe** [comment] 2019-06-22 16:42
Hmm yeah strange. We can leave the issue open for a bit in case someone else runs in to issues

**Comment by setrumbore** [comment] 2019-08-02 13:19
Hi from Sue --  I was having the same problem (download did not update to the latest version.  Good news = I read the thread instead of bugging someone personally
Bad news = I deleted the old files on my computer, and tried to load again using the same command as before:
> mydata<-ISRaD.getdata(directory = "~/Dropbox/IsRad_Data_base/R_scripts", dataset="full", extra = F)
The return is:
Error in gzfile(file) : invalid 'description' argument

It did download the readme.txt file into the proper folder but nothing else.....
I tried reinstalling the package and it still does the same thing.
Also tried changing the name of the destination file - that DID work
So overall, good news, just would be careful in deleting the old files from the old directory

**Comment by coreylawrence** [comment] 2019-08-06 23:12
I'm having a similar problem with the gzfile(file):invalid 'description' argument error returned as well. This happens after the zip file is downloaded but before it is unzipped and occurs with or without a copy of the database files already in the working directory.

I am able to expand the zip file and load data using lines of code from ISRaD.getdata but it fails at the unzip when I run the function. It seems like the problem is with the file path, either for the .zip, the destination folder for the unzip, or both. 

Anyways, this does seem like a problem that still needs to be addressed.

**Comment by aahoyt** [comment] 2019-08-06 23:42
Agreed. I have also continued to have issues sometimes (not always) when testing this. I'm running an ISRaD training at Livermore National Lab tomorrow, so I'll report back on how many people run into this.

**Comment by jb388** [comment] 2019-08-07 01:58
Seems like this "invalid 'description' argument" error is universal. But despite the error, the files seem to download for me anyway.

**Comment by aahoyt** [comment] 2019-08-07 14:47
Also, in case anyone is looking for a fast work around, you can:
(1) Download the full zip folder from this page: https://international-soil-radiocarbon-database.github.io/ISRaD/database/ (blue download link)
(2) load the R data object (.rda file) object into R using the command: "load( full fil path here)"

**Comment by christinaschaedel** [comment] 2019-08-09 09:48
I'm having an issue downloading the data as well and will use the work around approach for now

**Comment by greymonroe** [comment] 2019-08-10 08:33
for those with the issue, have you tried setting force_download = T in the get_data() function?

**Comment by jb388** [comment] 2019-08-10 14:02
@greymonroe get_data() seems to be working after the rebuild. Did you fix something specific?

**Comment by greymonroe** [comment] 2019-08-10 15:40
> @greymonroe get_data() seems to be working after the rebuild. Did you fix something specific?

@jb388 hmm no nothing that would explain why its working now.

**Comment by greymonroe** [comment] 2019-08-10 17:08
OK but now i did figure out what was wrong and it should be fixed.

Had to add some code to delete the old files. I also added some code so that users have to verify they want to delete the old files

**Comment by jb388** [comment] 2019-08-10 21:33
Ok, great. I thought it may have to do with the extra files. Good work---thanks!

**Closed** 2019-08-11 19:48 UTC

**Comment by christinaschaedel** [comment] 2019-08-12 09:32
yes, it worked for me too now. Thank you!
