### ISSUE TITLE
Error while creating the ISRaD_extra object

### ISSUE THREAD

**Issue by mguderle** [International-Soil-Radiocarbon-Database/ISRaD#173] opened 2019-02-25 10:58 UTC
Hi all,

while running the ISRaD.build function, I get the following error when the code tries to create the ISRaD_extra object:

Creating the ISRaD_extra object...
Error in `$<-.data.frame`(`*tmp*`, "lyr_dd14c", value = c(-172.4, -330.4,  : 
  replacement has 7101 rows, data has 7029
In addition: Warning message:
In database$layer$lyr_14c - calc_atm14c(database$layer, "lyr_obs_date_y")$atm14C :
  longer object length is not a multiple of shorter object length

I used the current version and also updated all packages.

Would be happy for some hints/help.

Best,
Marcus

**Comment by greymonroe** [comment] 2019-02-26 04:35
Hey Marcus,
I was unable to replicate the error. I have the most up to date version. Did this error occur when trying to add a new dataset?

**Comment by mguderle** [comment] 2019-02-26 06:15
Hey Grey,
yes it occurred while adding 2 new datasets. Do you have an idea what went wrong?

**Comment by greymonroe** [comment] 2019-02-26 14:19
Can you send me the two datasets? I will see if I can get the same error

**Comment by coreylawrence** [comment] 2019-02-26 14:36
The problematic dataset is linked in Marcus's post above. I had another look at the file, which passes qa/qc and don't see any immediate red flags. I'm guessing the issue derives from the fill extra function but may be triggered by something in this template. One possibility is the inclusion of two listings in the metadata table, the second of which is not referenced at any other level.

**Comment by greymonroe** [comment] 2019-02-28 15:02
I think the issue is because there is already Hall_2015 in the data files. Are these redundant?

**Comment by coreylawrence** [comment] 2019-02-28 15:07
Yes, the Hall_2015_2018.xls template is the original Hall_2015 template merged with some additional data reported in a separate publication. The Hall_2015 should be replaced by the new one.

**Comment by greymonroe** [comment] 2019-02-28 15:08
Ok great. Yes, removing Hall_2015.xlsx fixes the error.

**Closed** 2019-03-04 08:38 UTC
Labels: help wanted
