### ISSUE TITLE
Non-unique names for different sites/profiles/layers

### ISSUE THREAD

**Issue by alkalifly** [International-Soil-Radiocarbon-Database/ISRaD#90] opened 2018-11-01 21:35 UTC
At the moment, there is nothing to prevent name duplication between entries, so we have sites, profiles, and layers with non-unique names. This makes it tricky to get upstream information. For example, if I'm working with a layer and I want the land cover of that layer's profile, I cannot just check based on the pro_name of that layer, because there could be more than one profile with the same pro_name. Instead, I have to check entry_name, site_name, and pro_name all together to make sure I'm getting the correct information.

Is there any way that we could enforce unique names for these entries? Perhaps something in the compile function could check each name as it's being added, and if it finds it to be a duplicate, could append a random or sequential string to it? I imagine this would add a lot of processing time to the function, so it could certainly be optional, but it would save a lot of effort in the future when working with the data.

**Comment by jb388** [comment] 2018-11-02 07:15
This issue has cropped up a number of times. Enforcing unique names upstream of the user is next to impossible. While it's doable to reference multiple columns when looking for unique IDs, I find it easier to assign new names. In my typical workflow I create new index columns (just sequential numbers) with whatever the current version of the database is, at each level. I maintain the old names for reference back to the templates/papers, but use the new names for sorting. This could be added as a vignette/ISRaD.extra function.

**Comment by alkalifly** [comment] 2018-11-02 23:04
Thanks, Jeff. I am curious to understand your workflow with a new index column. How does that tell you, e.g., which entry on the profile tab goes with the layer you are looking at, if there is more than one profile with that layer's pro_name? 

Note: I am working with ISRaD_list.xlsx outside of R. If the R object has some way of linking each layer to its unique profile, even when the profile name is not unique, then that doesn't work here.

My temporary workaround has been to cross reference entries using a combination of entry_name, site_name, and pro_name. It's cumbersome, but more importantly, even that combination is not enforced as unique. There are profiles in the current version of ISRaD for which it is not possible to tell the site coordinates, because there is more than one site with the same name. I don't think your approach of creating new index columns could be of help with this.

At the moment, this is only a problem with one entry: McClung_de_Tapia_2005.xlsx. This template was generated from the He compilation, so I was able to go back to Yujie's original data and fix it (see issue #93). But these identical site names passed QAQC in this case, meaning this problem could come up with new templates in the future. It seems that at very least, QAQC should make sure that each site and profile name is unique in each individual template, so that as long as each new entry name is unique, there will be some unique combination of entry, site, and profile names.

**Comment by jb388** [comment] 2018-11-03 14:28
Hmm, I'm not quite sure I understand the issue. But I added an additional QAQC check to make sure site names aren't duplicated for a given entry (the prior version of QAQC only checked to make sure the site coordinates weren't duplicated). 

I guess if you are working with the data in excel this doesn't help, but within the R list object each layer is linked to its rightful profile even when the profile name itself isn't unique (i.e. dependencies are preserved).

**Comment by greymonroe** [comment] 2019-01-11 00:41
We discussed this today at Irvine and I think its an issue that we have figured out. New datasets should be checked by the ISRaD editor to verify that they are not a duplicate of another template.

**Closed by greymonroe** 2019-01-11 00:41 UTC
